Enable metadata service to track the events from a subset of namespaces
pixie-io/pixie pull request #1368
Opened 2023-05-25 08:58 UTC by MrAta

Summary: Enable metadata service to track the events from a subset of namespaces when desired, instead of tracking the events from the entire cluster.

Relevant Issues: #1364 

Type of change: /kind feature

Test Plan: WIP

2023-05-26 16:35 UTC, vihangm commented on src/vizier/services/metadata/metadata_server.go
> +	}
Can you explicitly declare this as a pflag in `init` and use that instead? Then you can make it a `StringSlice`.

2023-05-26 17:06 UTC, vihangm requested changes

2023-05-26 17:06 UTC, vihangm commented on src/vizier/services/metadata/metadata_server.go
> +	v1 "k8s.io/api/core/v1"
Looks like you need to run `gazelle` to update the build files to add this dep.
If you have `bazel` and the golang toolchain setup `make gazelle` at top of tree should do the trick.

2023-06-29 18:43 UTC, vihangm commented on src/vizier/services/metadata/metadata_server.go
> +	viper.BindEnv("metadata_namespaces")
This isn't necessary. Our shared service setup code will bind all flags to corresponding env vars with a `PL_` prefix.

2023-06-29 18:43 UTC, vihangm commented on src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_utils.go
>  	list, err := clientset.CoreV1().Pods(v1.NamespaceAll).List(context.Background(), metav1.ListOptions{})
the namespaces here need to also be restricted.

2023-07-01 20:13 UTC, vihangm commented
This looks mostly ok, but I think #1595 will actually make this easier by allowing us to filter in only one location (i.e. at the SharedIndexInformerFactory creation).

Also we should see if it's possible to add some testing coverage to ensure that the namespace restriction works as expected.

2023-07-02 02:50 UTC, MrAta commented
Thanks for the insights, @vihangm!
Re #1595, either of the PRs will need a rebase and conflict resolution once the other one is merged :D I'm not sure which way is more convenient, up to you.

Re the test case, I just added a simple test case for Pod creation only. Please let me know if it sounds right to you and I can add other resource types and events too.

2023-07-02 06:15 UTC, vihangm commented
Test case looks good. Adding a little bit of simple coverage on all resources types would be nice.

2023-07-04 07:29 UTC, MrAta commented
@vihangm add more test cases for other resource types.

2023-07-13 18:47 UTC, JamesMBartlett approved these changes
LGTM, discussed with @vihangm who's out at the moment and he said its good to go from his end. So if we can get the merge conflicts fixed we should be good to go. Sorry for the delay

2023-07-13 19:24 UTC, vihangm commented
Also can you update the test plan in the PR since this now has unit tests (and also should be tested with a dev deploy of vizier before merging).

2023-07-13 21:09 UTC, JamesMBartlett commented
I tested this out on a cluster, both with all namespaces and with a subset of namespaces and both seemed to work as expected.

2023-07-14 01:01 UTC, JamesMBartlett approved these changes

2023-07-14 01:23 UTC, merged