Adding support for connecting standalone PEM in pxapi
pixie-io/pixie pull request #1444
Opened 2023-06-07 02:16 UTC by RagalahariP

Summary: Adding support for connecting standalone PEM in `pxapi`. 

Test Plan: Added an example program to connect standalone PEM

2023-06-07 02:25 UTC, RagalahariP commented
To add, observed that `vizierID`  in `NewVizierClient()` is not getting used while extracting results from standalonePEM .  Please correct my observation.

2023-07-14 17:31 UTC, aimichelle requested changes

2023-08-07 16:07 UTC, RagalahariP commented on src/api/go/pxapi/client.go
> +func (c *Client) initLocalClient(ctx context.Context) error {
@aimichelle Thank you for review. Updated code as suggested.

2023-11-02 19:28 UTC, JamesMBartlett commented on src/api/go/pxapi/client.go
> +	if (strings.Contains(c.directAddr, "0.0.0.0") == true) {
This check should be `c.directAddr != ""`

2023-11-02 19:28 UTC, JamesMBartlett commented on src/api/go/pxapi/client.go
> +        conn, err := grpc.Dial(c.directAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
I think we should take the credentials in as another `ClientOption` eg `WithDirectCreds`

2023-11-09 16:22 UTC, vihangm commented
Looks like this was covered by #1762

2023-11-09 16:22 UTC, closed without merging