[standalone_pem] Fully static link.
pixie-io/pixie pull request #1713
Opened 2023-09-27 17:48 UTC by etep

Summary: We fully static link the standalone pem binary and a few other stirling binaries. This enables the binaries to run on any host i.e. without needing certain dynamic libraries (`.so` files) installed.

Type of change: /kind feature

Test Plan: Existing tests. And, copied the standalone pem binary to a GKE node, then deleted all libs, then ran the binary. The binary ran (but could not find linux headers).

2023-09-27 20:25 UTC, ddelnano commented on src/experimental/standalone_pem/BUILD.bazel
>  pl_cc_binary(
Did you consider linking a different libc like musl? I believe static linking glibc is generally [discouraged](https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged), although I don't have experience with these problems.

2024-01-11 17:49 UTC, JamesMBartlett requested changes
Fully statically linking GCC will cause unexpected errors, especially with network calls. If we want to do fully statically linked binaries we have to use musl.

2024-01-11 17:55 UTC, etep commented
Agreed, needs to use `musl`. How much scope is there in switching to `musl` ... is that something like a new `cc_toolchain`?

2024-01-18 19:20 UTC, closed without merging

2024-01-18 19:20 UTC, etep commented
It is not ok to statically link to glibc. Planning to setup a tool chain to use `musl` for this purpose.