[perf_tool] Add BatchInserter for bigquery
pixie-io/pixie pull request #961
Opened 2023-03-03 22:19 UTC by JamesMBartlett

Summary: BigQuery `Inserter().Put` calls can be quite slow, so we don't want to run that for every single metric row we receive during an experiment.
This adds a utility that reads from a channel of arbitrary data, and batches it up before sending it to bigquery. This reduces the number of `Put` calls.

Type of change: /kind test-infra

Test Plan: Tested that rows sent to the BatchInserter show up in bigquery. Also tested that if not enough rows are sent the timeout will trigger a push anyway.

2023-03-03 23:36 UTC, vihangm requested changes

2023-03-03 23:36 UTC, vihangm commented on src/e2e_test/perf_tool/pkg/bq/batch_inserter.go
> +				}
I think you can remove the need for mutex-es and a separate watchdog by combining these.

something like:
```
func (b* BatchInserter) Run(data <- ch interface{}) {
  for {
    select {
    case <-t.C:
      b.Upload()
    case datum := <-data:
      if len(batch) >= maxLen:
        b.Upload()
      b.Add(datum)
    }
  }
}
```

2023-03-03 23:36 UTC, vihangm commented on src/e2e_test/perf_tool/pkg/bq/batch_inserter.go
> +				time.Sleep(5 * time.Second)
why is this sleep here?

2023-03-06 22:34 UTC, zasgar approved these changes

2023-03-06 23:50 UTC, merged